name: week_3_blabla_project
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.6.0
 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0
 
flutter:
  uses-material-design: true
  fonts:
    - family: Eesti
      fonts:
        - asset: assets/fonts/GT-Eesti-Bold.otf
        - asset: assets/fonts/GT-Eesti-Light.otf
        - asset: assets/fonts/GT-Eesti-Regular.otf
        - asset: assets/fonts/GT-Eesti-Thin.otf
 
  assets:
    - assets/images/
 

  # To add assets to your application, add an assets section, like this:
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
